language: python
python: "3.7"
  
install:
  - pip install -U -r requirements.txt

script:
  - python -m pytest --ignore=prototype --cov-report term --cov=MPyDATA
  - |
    python -m ipykernel install --user
    for i in MPyDATA_examples/*/*.ipynb; do 
      jupyter nbconvert --to markdown --stdout $i > $i.md.repo; 
      jupyter nbconvert --to markdown --execute --stdout $i > $i.md.travis; 
      # TEMPORARILY disabled before we find a solution for generated graphics causing diffs to differ
      # diff $i.md.repo $i.md.travis
    done;

after_success:
  - codecov
